using System;

public class Class1
{
	public Class1()
	{
        //el bucle for es de tipo determinado
        //permite repetir un bloque de código un número específico de veces. Es una de las estructuras de control más utilizadas y poderosas.

        for (initialization; condition; update)
        {
            // hacer algo
        }

        /*
         * 
         for(initialization; condition; update)
        {
    	     // hacer algo
        }   
         */

        //Estructura en c#

        for (int i = 0; i < 100; i++)
        {
            // hacer algo
        }
    }
}
